package:
  name: intake-netflow
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - attrs
    - intake>=0.2
    - python

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - py.test --verbose --cov=intake_netflow tests

about:
  home: https://github.com/ContinuumIO/intake-netflow
  license: BSD
  license_file: LICENSE
  summary: Intake Netflow plugin
